/** India passenger-car make/model list used to flag `availableInIndia`. */

export const INDIA_CAR_CATALOG: Record<string, string[]> = {
  'Ashok Leyland': ['Stile'],
  'Aston Martin': [
    'DB11',
    'DB9',
    'DBS',
    'DBX',
    'Rapide',
    'V12 Vantage',
    'V8 Vantage',
    'Vanquish',
    'Vantage',
    'Virage',
  ],
  Audi: [
    'A3 Cabriolet',
    'A3',
    'A4',
    'A5 Cabriolet',
    'A5',
    'A6',
    'A7',
    'A8 L',
    'e-tron Sportback',
    'e-tron GT',
    'e-tron',
    'Q2',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'R8',
    'RS5',
    'RS6',
    'RS7 Sportback',
    'RS7 Sportsback',
    'RS Q8',
    'S4',
    'S5 Sportback',
    'S6',
    'S8',
    'TT',
  ],
  Austin: ['Cambridge'],
  Bentley: [
    'Arnage',
    'Azure',
    'Bentayga',
    'Continental Flying Spur',
    'Continental GT',
    'Continental GTC',
    'Continental Super Sports',
    'Mulsanne',
  ],
  BMW: [
    '2 Series Gran Coupe',
    '3 Series Gran Limousine',
    '3 Series GT',
    '3 Series',
    '5 Series GT',
    '5 Series',
    '6 Series Gran Coupe',
    '6 Series GT',
    '6 Series',
    '7 Series',
    '8 Series',
    '1 Series',
    'i4',
    'i8',
    'iX',
    'M340i',
    'M4 Competition',
    'M2',
    'M3',
    'M4',
    'M5',
    'M6',
    'M8',
    'X3 M',
    'X5 M',
    'X1',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'XM',
    'Z3',
    'Z4',
  ],
  Bugatti: ['Veyron'],
  BYD: ['Atto 3', 'e6'],
  Cadillac: ['CTS', 'Escalade', 'Limousine'],
  Caterham: ['7'],
  Chevrolet: [
    'Aveo U-VA',
    'Aveo',
    'Beat',
    'Camaro',
    'Captiva',
    'Corvette',
    'Cruze',
    'Enjoy',
    'Fleetline',
    'Forester',
    'Impala',
    'Optra Magnum',
    'Optra SRV',
    'Optra',
    'Sail Hatchback',
    'Sail U-VA',
    'Sail',
    'Silverado',
    'Spark',
    'Tavera',
    'Tourer',
    'Trailblazer',
  ],
  Chrysler: ['300', 'Avenger', 'Grand Voyager'],
  Citroen: ['C3', 'C5 Aircross'],
  Daewoo: ['Cielo', 'Matiz', 'Nexia'],
  Datsun: ['GO Plus', 'GO+', 'redi-GO', 'GO'],
  DC: ['Avanti'],
  Dodge: ['Nitro'],
  'Eicher Polaris': ['Multix'],
  Ferrari: [
    '575 Superamerica',
    '599 GTB Fiorano',
    'F12berlinetta',
    'F8 Tributo',
    'GTC4 Lusso',
    'California',
    'Portofino',
    'Gallardo',
    '360',
    '458',
    '488',
    '612',
    '812',
    'F430',
    'FF',
    'Roma',
  ],
  Fiat: [
    'Abarth 595',
    'Abarth Punto',
    'Palio Stile',
    'Palio NV',
    'Punto Evo',
    'Punto Pure',
    'Siena Weekend',
    'Urban Cross',
    'Linea Classic',
    'Adventure',
    'Avventura',
    'Millicento',
    'Palio D',
    'Petra D',
    '1100',
    '500',
    'Linea',
    'Palio',
    'Petra',
    'Punto',
    'Siena',
    'Uno',
  ],
  'Force Motors': ['Force One', 'Gurkha', 'Trax Cruiser'],
  Ford: [
    'Aspire',
    'Capri',
    'Classic',
    'EcoSport',
    'Endeavour',
    'Escort',
    'Fiesta Classic',
    'Fiesta',
    'Figo',
    'Freestyle',
    'Fusion',
    'Ikon',
    'Model T',
    'Mondeo',
    'Mustang',
    'Raptor',
    'Zephyr',
  ],
  GMC: ['Sierra 2500'],
  'Hindustan Motors': ['Ambassador', 'Contessa'],
  Holden: ['Commodore'],
  Honda: [
    'City Hybrid eHEV',
    'All New City',
    'City ZX',
    'Step WGN',
    'Accord',
    'Amaze',
    'Brio',
    'BR-V',
    'Civic',
    'Concerto',
    'CR-V',
    'CR-X',
    'Jazz',
    'Mobilio',
    'WR-V',
    'City',
  ],
  Humber: ['Hawk'],
  Hummer: ['H2', 'H3'],
  Hyundai: [
    'Grand i10 Nios',
    'Fluidic Verna 4S',
    'Venue N Line',
    'i20 N Line',
    'i20 Active',
    'Elite i20',
    'Grand i10',
    'Kona Electric',
    'Santro Xing',
    'Sonata Embera',
    'Sonata Transform',
    'Verna Transform',
    'Verna 2020',
    'Accent Viva',
    'Getz Prime',
    'Alcazar',
    'Accent',
    'Aura',
    'Creta',
    'Elantra',
    'Eon',
    'Getz',
    'i10',
    'i20',
    'Santa Fe',
    'Santro',
    'Sonata',
    'Terracan',
    'Tucson',
    'Venue',
    'Verna',
    'Xcent',
  ],
  ICML: ['Extreme', 'Rhino Rx'],
  Isuzu: ['D-Max V-Cross', 'D-Max', 'MU7', 'MU-X', 'Trooper'],
  Jaguar: ['F-Pace', 'F-Type', 'I-Pace', 'XE', 'XF', 'XJ L', 'XK'],
  Jeep: ['Grand Cherokee', 'Cherokee', 'Compass', 'Kaiser', 'Meridian', 'Willys', 'Wrangler'],
  Kia: ['Carens 2022', 'Seltos 2022', 'Sonet 2022', 'Carnival', 'EV6', 'Seltos', 'Sonet'],
  Lamborghini: [
    'Aventador Ultimae',
    'Huracan Evo Spyder',
    'Huracan Tecnica',
    'Huracan Evo',
    'Huracan STO',
    'Urus Performante',
    'Aventador',
    'Gallardo',
    'Murcielago',
    'Urus',
  ],
  'Land Rover': [
    'Range Rover Evoque',
    'Range Rover Sport',
    'Range Rover Velar',
    'Discovery Sport',
    'Discovery 3',
    'Discovery 4',
    'Freelander 2',
    'Range Rover',
    'Defender',
    'Discovery',
  ],
  Lexus: [
    'LC 500h',
    'GS 300',
    'GS 350',
    'LS 400',
    'LS 430',
    'LS 460',
    'LS 600',
    'LX 470',
    'LX 570',
    'SC 430',
    'ES',
    'LS',
    'LX',
    'NX',
    'RX',
  ],
  Lotus: ['Evora'],
  Mahindra: [
    'XUV300 TurboSport',
    'Scorpio Getaway',
    'Scorpio 2021',
    'Bolero Neo',
    'Alturas G4',
    'e2o PLUS',
    'KUV100 NXT',
    'Verito Vibe CS',
    'Scorpio N',
    'NuvoSport',
    'Armada',
    'Bolero',
    'e2o',
    'Jeep',
    'KUV100',
    'Marazzo',
    'Marshal',
    'Quanto',
    'REVAi',
    'Scorpio',
    'Thar',
    'TUV300',
    'Verito',
    'Voyager',
    'XUV300',
    'XUV500',
    'XUV700',
    'Xylo',
  ],
  'Mahindra-Renault': ['Logan Edge', 'Logan'],
  Maini: ['REVAi', 'Reva'],
  'Maruti Suzuki': [
    'Alto K10',
    'Alto 800',
    'Wagon R 1.0',
    'Vitara Brezza',
    'Grand Vitara',
    'Swift Dzire',
    'Celerio X',
    'S-Presso',
    'S-Cross',
    'A-Star',
    'Baleno',
    'Brezza',
    'Celerio',
    'Ciaz',
    'Dzire',
    'Eeco',
    'Ertiga',
    'Esteem',
    'Estilo',
    'Gypsy',
    'Ignis',
    'Kizashi',
    'Omni',
    'Ritz',
    'Stingray',
    'Swift',
    'SX4',
    'Versa',
    'Wagon R',
    'XL6',
    'Zen',
    'Alto',
    '1000',
    '800',
  ],
  Maserati: [
    'GranTurismo (2009)',
    'GranTurismo',
    'GranCabrio',
    'Quattroporte',
    'Ghibli',
    'Levante',
    'MC20',
  ],
  Maybach: ['57 S', '57', '62'],
  Mazda: ['Miata', 'RX-8', 'Sentia'],
  McLaren: ['720S', 'GT'],
  'Mercedes-Benz': [
    'AMG GT 4-Door Coupe',
    'AMG GLC43 Coupe',
    'AMG GLE Coupe',
    'AMG GLA35',
    'AMG A45 S',
    'AMG A35',
    'AMG E53',
    'AMG E63',
    'AMG EQS',
    'AMG GT',
    'A-Class Limousine',
    'E-Class All Terrain',
    'E-Class Cabriolet',
    'C-Class Cabriolet',
    'S-Class Cabriolet',
    'Maybach S-Class',
    'Maybach GLS',
    'S-Class (W222)',
    'GLC Coupe',
    'GLE Coupe',
    'A-Class',
    'B-Class',
    'C-Class',
    'C-Coupe',
    'E-Class',
    'G-Class',
    'M-Class',
    'R-Class',
    'S-Class',
    'S-Coupe',
    'SLK-Class',
    'SLS AMG',
    'V-Class',
    'MB-Class',
    'MB 100',
    'CLA',
    'CLK',
    'CLS',
    'EQB',
    'EQC',
    'EQS',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'GL',
    'SLC',
    'SLK',
    'SDL',
    'SL',
    'Viano',
    'W123',
    '190',
    '200',
  ],
  MG: ['Hector Plus', 'Astor', 'Gloster', 'Hector', 'ZS EV'],
  MINI: [
    'Cooper Convertible',
    'Cooper Countryman',
    'Cooper JCW',
    'Cooper SE',
    'Cooper S',
    'Countryman',
    'Clubman',
    'Cooper',
  ],
  Mitsubishi: [
    'Lancer Evolution',
    'Pajero Sport',
    'Outlander',
    'Challenger',
    'Cedia',
    'Galant',
    'Lancer',
    'Montero',
    'Pajero',
    'FTO',
    'GTO',
  ],
  Morris: ['Minor'],
  Nissan: [
    'Safari Granroad',
    'Fairlady 300 ZX',
    'Micra Active',
    'Bluebird',
    'Cedric',
    'Evalia',
    'Gloria',
    'Infiniti',
    'Jonga',
    'Laurel',
    'Magnite',
    'Murano',
    'NV350',
    'Serena',
    'Sunny',
    'Teana',
    'Terrano',
    'X-Trail',
    '350Z',
    '370Z',
    'Cima',
    'GT-R',
    'Kicks',
    'Micra',
  ],
  Opel: ['Astra', 'Corsa', 'Vectra'],
  Peugeot: ['309'],
  Pontiac: ['Bonneville'],
  Porsche: [
    'Taycan Cross Turismo',
    'Cayenne Coupe',
    'Carrera GT',
    'Boxster',
    'Cayenne',
    'Cayman',
    'Macan',
    'Panamera',
    'Taycan',
    '718',
    '911',
  ],
  Premier: ['118 NE', '138 D', 'Padmini', 'Rio'],
  Renault: [
    'Captur',
    'Duster',
    'Fluence',
    'Kiger',
    'Koleos',
    'Kwid',
    'Lodgy',
    'Megane',
    'Pulse',
    'Scala',
    'Scenic',
    'Triber',
  ],
  'Rolls-Royce': [
    'Ghost Series II',
    'Drophead Coupe',
    'Phantom Coupe',
    'Phantom VIII',
    'Cullinan',
    'Phantom',
    'Wraith',
    'Dawn',
    'Ghost',
  ],
  SAAB: ['9-3'],
  San: ['Storm'],
  Sipani: ['Montego'],
  Skoda: [
    'Octavia Combi',
    'Fabia Scout',
    'Rapid TSI',
    'Fabia',
    'Karoq',
    'Kodiaq',
    'Kushaq',
    'Laura',
    'Octavia',
    'Rapid',
    'Slavia',
    'Superb',
    'Yeti',
  ],
  Smart: ['Fortwo'],
  Ssangyong: ['Rexton'],
  Studebaker: ['Champion'],
  Subaru: ['Impreza', 'J10'],
  Tata: [
    'Nexon EV Prime',
    'Nexon EV Max',
    'Safari Storme 2019',
    'Sumo Grande MK II',
    'Indica Vista',
    'Indigo Marina',
    'Safari Storme',
    'Sumo Grande',
    'Sumo Spacio',
    'Sumo Victa',
    'Sumo Gold',
    'Tiago NRG',
    'Tiago JTP',
    'Tigor JTP',
    'Vista Tech',
    'Xenon XT',
    'Nano GenX',
    'Indica eV2',
    'Indica V2',
    'Indigo eCS',
    'Indigo CS',
    'Indigo XL',
    'Nexon EV',
    'Tiago EV',
    'Tigor EV',
    'Altroz',
    'Aria',
    'Bolt',
    'Estate',
    'Harrier',
    'Hexa',
    'Indicab',
    'Indica',
    'Indigo',
    'Manza',
    'Movus',
    'Nano',
    'Nexon',
    'Punch',
    'Safari',
    'Sierra',
    'Sumo',
    'Tiago',
    'Tigor',
    'Venture',
    'Winger',
    'Zest',
    'TL',
  ],
  Toyota: [
    'Urban Cruiser Hyryder',
    'Fortuner Legender',
    'Platinum Etios',
    'Innova Hycross',
    'Innova Crysta',
    'Corolla Altis',
    'Corolla Ceres',
    'Corolla Levin',
    'Etios Cross',
    'Etios Liva',
    'Land Cruiser Prado',
    'Land Cruiser',
    'Alphard 2017',
    'FJ Cruiser',
    'Urban Cruiser',
    'Alphard',
    'Camry',
    'Celica',
    'Commuter',
    'Corolla',
    'Corona',
    'Cressida',
    'Cresta',
    'Crown',
    'Cynos',
    'Estima',
    'Etios',
    'Fortuner',
    'Glanza',
    'Hiace',
    'Hilux',
    'Innova',
    'Lexus',
    'Majesta',
    'Mark II',
    'MasterAce',
    'MR2',
    'Prius',
    'Qualis',
    'RAV-4',
    'Sera',
    'Tercel',
    'Vellfire',
    'Ventury',
    'Yaris',
  ],
  Volkswagen: [
    'Tiguan AllSpace',
    'Virtus 2022',
    'Taigun 2021',
    'Cross Polo',
    'Caravelle',
    'Transporter',
    'Touareg',
    'Phaeton',
    'Beetle',
    'Passat',
    'Tiguan',
    'T-Roc',
    'Ameo',
    'GTI',
    'Jetta',
    'Polo',
    'Vento',
    '1600',
  ],
  Volvo: [
    'V40 Cross Country',
    'V90 Cross Country',
    'XC40 Recharge',
    'S40',
    'S60',
    'S80',
    'S90',
    'V40',
    'V70',
    'XC40',
    'XC60',
    'XC90',
  ],
  Willys: ['CJ3B', 'CJ-5', 'MB'],
};

const BRAND_ALIASES: Record<string, string[]> = {
  'maruti suzuki': ['maruti'],
  'mercedes-benz': ['mercedes benz', 'mercedes'],
  'rolls-royce': ['rolls royce', 'rollsroyce'],
  'land rover': ['landrover'],
  'force motors': ['force'],
  'hindustan motors': ['hindustan'],
  'eicher polaris': ['eicher'],
  'ashok leyland': ['ashok leyland'],
  'mahindra-renault': ['mahindra renault'],
  citroen: ['citroën'],
};

export function normalizeIndiaCarToken(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9+]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function brandCandidates(catalogBrand: string): string[] {
  const key = normalizeIndiaCarToken(catalogBrand);
  const extra = BRAND_ALIASES[key] ?? [];
  return [key, ...extra];
}

export function manufacturerMatchesIndiaBrand(
  manufacturerName: string,
  catalogBrand: string,
): boolean {
  const hay = normalizeIndiaCarToken(manufacturerName);
  if (!hay) return false;
  return brandCandidates(catalogBrand).some((brand) => {
    if (brand.length <= 2) {
      return hay === brand || hay.startsWith(`${brand} `) || hay.endsWith(` ${brand}`);
    }
    return hay === brand || hay.includes(brand) || brand.includes(hay);
  });
}

function haystackContainsModel(haystack: string, model: string): boolean {
  const needle = normalizeIndiaCarToken(model);
  if (!needle) return false;
  const padded = ` ${haystack} `;
  return padded.includes(` ${needle} `);
}

export function vehicleMatchesIndiaCatalog(input: {
  manufacturerName: string;
  name: string;
  model: string;
  variant?: string | null;
}): boolean {
  const hay = normalizeIndiaCarToken(
    `${input.name} ${input.model} ${input.variant ?? ''} ${input.manufacturerName}`,
  );
  for (const [brand, models] of Object.entries(INDIA_CAR_CATALOG)) {
    if (!manufacturerMatchesIndiaBrand(input.manufacturerName, brand)) continue;
    const sorted = [...models].sort((a, b) => b.length - a.length);
    if (sorted.some((model) => haystackContainsModel(hay, model))) return true;
  }
  return false;
}
