import { z } from 'zod';
import { jsonValueSchema, publishStatusSchema, slugSchema, uuidSchema } from './common';

const optionalUrl = z.union([z.string().url(), z.literal(''), z.null()]).optional();
const optionalEmail = z.union([z.string().email(), z.literal(''), z.null()]).optional();

/** Fix truncated schemes like `ttps://` from a missing `h` in the admin form. */
export function normalizeHttpPublicUrl(raw: string | null | undefined): string | null {
  if (raw == null) return null;
  let value = raw.trim();
  if (!value) return null;
  if (value.startsWith('ttps://')) value = `h${value}`;
  else if (value.startsWith('tp://')) value = `ht${value}`;
  else if (value.startsWith('//')) value = `https:${value}`;
  else if (!/^[a-z][a-z0-9+.-]*:/i.test(value)) value = `https://${value}`;
  return value.replace(/\/+$/, '');
}

const gcsPublicBaseUrl = z
  .union([z.string(), z.literal(''), z.null()])
  .optional()
  .transform((value) => normalizeHttpPublicUrl(value ?? null))
  .refine((value) => value === null || /^https?:\/\//i.test(value), {
    message: 'Public / CDN base URL must start with https://',
  });

function blankToNull(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed || null;
}

const optionalCompanyEmail = z
  .union([z.string(), z.null()])
  .optional()
  .transform((value) => blankToNull(value))
  .refine((value) => value === null || z.string().email().safeParse(value).success, {
    message: 'Enter a valid email address, or leave this blank.',
  });

const optionalCompanyUrl = z
  .union([z.string(), z.null()])
  .optional()
  .transform((value) => normalizeHttpPublicUrl(blankToNull(value)))
  .superRefine((value, ctx) => {
    if (value !== null && !z.string().url().safeParse(value).success) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'Enter a valid URL, such as https://example.com, or leave this blank.',
      });
    }
  });

const optionalCompanyPan = z
  .union([z.string(), z.null()])
  .optional()
  .transform((value) => {
    const trimmed = blankToNull(value);
    return trimmed ? trimmed.toUpperCase() : null;
  })
  .refine((value) => value === null || /^[A-Z]{5}[0-9]{4}[A-Z]$/.test(value), {
    message: 'PAN must be 10 characters, such as ABCDE1234F.',
  });

export const companyProfileSchema = z.object({
  legalName: z
    .string()
    .trim()
    .max(200, 'Legal name must be 200 characters or fewer.')
    .optional()
    .nullable(),
  address: z
    .string()
    .trim()
    .max(500, 'Address must be 500 characters or fewer.')
    .optional()
    .nullable(),
  city: z.string().trim().max(80, 'City must be 80 characters or fewer.').optional().nullable(),
  state: z.string().trim().max(80, 'State must be 80 characters or fewer.').optional().nullable(),
  postalCode: z
    .string()
    .trim()
    .max(12, 'Postal code must be 12 characters or fewer.')
    .optional()
    .nullable(),
  country: z
    .string()
    .trim()
    .max(80, 'Country must be 80 characters or fewer.')
    .optional()
    .nullable(),
  email: optionalCompanyEmail,
  phone: z.string().trim().max(40, 'Phone must be 40 characters or fewer.').optional().nullable(),
  website: optionalCompanyUrl,
  gstin: z
    .string()
    .trim()
    .max(15, 'GSTIN must be 15 characters or fewer.')
    .optional()
    .nullable()
    .refine(
      (value) => !value || /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$/i.test(value),
      'GSTIN must be 15 characters, such as 22AAAAA0000A1Z5.',
    ),
  pan: optionalCompanyPan,
  cin: z.string().trim().max(21, 'CIN must be 21 characters or fewer.').optional().nullable(),
  logoUrl: optionalCompanyUrl,
  payslipGeneratedBy: z
    .string()
    .trim()
    .max(120, 'Payslip generated by must be 120 characters or fewer.')
    .optional()
    .nullable(),
});

export const generalSettingsSchema = z.object({
  siteName: z.string().min(1).max(120).default('Varnarc'),
  siteTagline: z.string().max(200).optional().nullable(),
  logoUrl: optionalUrl,
  faviconUrl: optionalUrl,
  contactEmail: optionalEmail,
  contactPhone: z.string().max(40).optional().nullable(),
  copyrightText: z.string().max(300).optional().nullable(),
  companyName: z.string().max(150).optional().nullable(),
  companyAddress: z.string().max(500).optional().nullable(),
  timezone: z.string().max(60).default('UTC'),
  locale: z.string().max(10).default('en'),
});

export const maintenanceSettingsSchema = z.object({
  enabled: z.boolean().default(false),
  message: z.string().max(1000).optional().nullable(),
  readOnly: z.boolean().default(false),
  scheduledFrom: z.string().datetime().optional().nullable(),
  scheduledUntil: z.string().datetime().optional().nullable(),
  allowedIps: z.array(z.string()).default([]),
  bypassRoles: z.array(z.string()).default([]),
});

export const securitySettingsSchema = z.object({
  rateLimitPerMinute: z.number().int().min(1).max(10000).default(120),
  corsOrigins: z.array(z.string()).default([]),
  cspEnabled: z.boolean().default(false),
  cspReportOnly: z.boolean().default(true),
  allowedOrigins: z.array(z.string()).default([]),
  apiKeyRequired: z.boolean().default(false),
  passwordMinLength: z.number().int().min(6).max(128).default(8),
});

export const cmsDefaultsSettingsSchema = z.object({
  defaultArticleStatus: publishStatusSchema.default('DRAFT'),
  autoSaveEnabled: z.boolean().default(true),
  autoSaveIntervalSeconds: z.number().int().min(10).max(600).default(60),
  revisionLimit: z.number().int().min(0).max(500).default(50),
});

export const seoDefaultsSettingsSchema = z.object({
  defaultTitle: z.string().max(70).optional().nullable(),
  defaultDescription: z.string().max(160).optional().nullable(),
  defaultOgImage: optionalUrl,
  titleSeparator: z.string().max(10).default('|'),
  robotsIndexDefault: z.boolean().default(true),
});

const adsenseClientIdSchema = z
  .union([
    z.string().regex(/^ca-pub-\d+$/i, 'Must be a ca-pub-… publisher ID'),
    z.literal(''),
    z.null(),
  ])
  .optional();

const adsenseSlotIdSchema = z
  .union([z.string().max(40).regex(/^\d*$/, 'Slot ID must be numeric'), z.null()])
  .optional();

export const adsenseSettingsSchema = z.object({
  enabled: z.boolean().default(true),
  client: adsenseClientIdSchema,
  defaultSlot: adsenseSlotIdSchema,
  slots: z.record(z.string().min(1).max(80), z.string().max(40).regex(/^\d+$/)).default({}),
});

export const gcsSettingsSchema = z.object({
  enabled: z.boolean().default(false),
  bucket: z.string().max(222).optional().nullable(),
  projectId: z.string().max(128).optional().nullable(),
  clientEmail: z.union([z.string().email(), z.literal(''), z.null()]).optional(),
  /** Empty string keeps the stored key; send a new PEM to replace. */
  privateKey: z.string().max(12000).optional().nullable(),
  /** When true, wipe the stored PEM and use Cloud Run ADC. */
  clearPrivateKey: z.boolean().optional(),
  publicBaseUrl: gcsPublicBaseUrl,
  makePublic: z.boolean().default(false),
});

export const auth0SettingsSchema = z.object({
  enabled: z.boolean().default(true),
  domain: z.string().max(200).optional().nullable(),
  clientId: z.string().max(200).optional().nullable(),
  /** Empty string keeps the stored secret. */
  clientSecret: z.string().max(500).optional().nullable(),
  /** Empty string keeps the stored cookie secret. */
  secret: z.string().max(500).optional().nullable(),
  clearClientSecret: z.boolean().optional(),
  clearSecret: z.boolean().optional(),
  audience: z.string().max(300).optional().nullable(),
  issuerBaseUrl: optionalUrl,
  connection: z.string().max(120).optional().nullable(),
});

export const upsertSettingSchema = z.object({
  key: z.string().min(1).max(120),
  value: jsonValueSchema,
  group: z.string().min(1).max(60).default('general'),
});

export const upsertFeatureFlagSchema = z.object({
  key: z.string().min(1).max(120),
  name: z.string().min(1).max(150),
  description: z.string().max(500).optional().nullable(),
  enabled: z.boolean().default(false),
  metadata: jsonValueSchema.optional().nullable(),
});

export const createHomepageLayoutSchema = z.object({
  name: z.string().min(1).max(150),
  slug: slugSchema,
  isDefault: z.boolean().default(false),
  sections: z
    .array(
      z.object({
        name: z.string().min(1).max(120),
        sortOrder: z.number().int().nonnegative().default(0),
        settings: jsonValueSchema.optional().nullable(),
        widgets: z
          .array(
            z.object({
              widgetId: uuidSchema,
              sortOrder: z.number().int().nonnegative().default(0),
              settings: jsonValueSchema.optional().nullable(),
            }),
          )
          .default([]),
      }),
    )
    .default([]),
});

export const updateHomepageLayoutSchema = createHomepageLayoutSchema;

export type GeneralSettingsInput = z.infer<typeof generalSettingsSchema>;
export type CompanyProfileInput = z.infer<typeof companyProfileSchema>;
export type MaintenanceSettingsInput = z.infer<typeof maintenanceSettingsSchema>;
export type SecuritySettingsInput = z.infer<typeof securitySettingsSchema>;
export type CmsDefaultsSettingsInput = z.infer<typeof cmsDefaultsSettingsSchema>;
export type SeoDefaultsSettingsInput = z.infer<typeof seoDefaultsSettingsSchema>;
export type AdsenseSettingsInput = z.infer<typeof adsenseSettingsSchema>;
export type GcsSettingsInput = z.infer<typeof gcsSettingsSchema>;
export type Auth0SettingsInput = z.infer<typeof auth0SettingsSchema>;
export type UpsertSettingInput = z.infer<typeof upsertSettingSchema>;
export type UpsertFeatureFlagInput = z.infer<typeof upsertFeatureFlagSchema>;
export type CreateHomepageLayoutInput = z.infer<typeof createHomepageLayoutSchema>;
export type UpdateHomepageLayoutInput = z.infer<typeof updateHomepageLayoutSchema>;
