ALTER TABLE "hr_salaries" ADD COLUMN IF NOT EXISTS "provident_fund" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "hr_payslips" ADD COLUMN IF NOT EXISTS "provident_fund" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "hr_salary_hikes" ADD COLUMN IF NOT EXISTS "previous_provident_fund" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "hr_salary_hikes" ADD COLUMN IF NOT EXISTS "provident_fund" DECIMAL(12,2) NOT NULL DEFAULT 0;
