import Link from 'next/link';
import { PageHeader } from '@varnarc/ui';
import { HrRecordForm } from '@/components/hr-record-form';
import { HrDataTable, HrPanel } from '@/components/hr-table';
import { apiServerFetch } from '@/lib/api';

type Employee = { id: string; fullName: string; employeeCode: string; status: string };
type Salary = {
  basic: string;
  hra: string;
  specialAllowance: string;
  leaveTravelAllowance: string;
  professionalTax: string;
  providentFund: string;
  employee: { fullName: string; employeeCode: string };
};
type Run = { id: string; period: string; status: string; _count: { payslips: number } };

function money(value: string) {
  return Number(value).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

export default async function HrPayrollPage() {
  const [employees, salaries, runs] = await Promise.all([
    apiServerFetch<Employee[]>('/hr/employees'),
    apiServerFetch<Salary[]>('/hr/salaries'),
    apiServerFetch<Run[]>('/hr/payroll'),
  ]);
  const active = (employees.data ?? []).filter((employee) => employee.status === 'ACTIVE');

  return (
    <div>
      <PageHeader
        title="Payroll"
        description="Set earnings and professional tax, then generate a monthly payslip. Net pay is gross pay minus professional tax."
      />
      {salaries.error ? <p className="mb-4 text-sm text-red-600">{salaries.error}</p> : null}
      <HrPanel>
        <HrRecordForm
          action="/api/admin/hr/salaries"
          submitLabel="Save salary"
          fields={[
            {
              name: 'employeeId',
              label: 'Employee',
              type: 'select',
              required: true,
              options: active.map((employee) => ({
                value: employee.id,
                label: `${employee.fullName} (${employee.employeeCode})`,
              })),
            },
            { name: 'basic', label: 'Basic', type: 'number', required: true },
            { name: 'hra', label: 'House rent allowance', type: 'number' },
            { name: 'specialAllowance', label: 'Special allowance', type: 'number' },
            { name: 'leaveTravelAllowance', label: 'Leave and travel allowance', type: 'number' },
            { name: 'professionalTax', label: 'Professional tax', type: 'number' },
            { name: 'providentFund', label: 'Provident fund (PF)', type: 'number' },
          ]}
        />
      </HrPanel>
      <HrPanel>
        <HrRecordForm
          action="/api/admin/hr/payroll/generate"
          submitLabel="Generate payslips"
          reportPayrollEmail
          fields={[
            { name: 'period', label: 'Month (YYYY-MM)', required: true },
            { name: 'generatedBy', label: 'Generated by (optional)' },
          ]}
        />
        <p className="mt-3 text-xs text-[var(--varnarc-subtle)]">
          Salary comes from the employee form. The company legal name, address, and default
          “generated by” name come from Settings → Company profile. Use a month such as 2026-10.
          Generating again for the same month refreshes the slips and emails each employee who has
          an email address.{' '}
          <Link className="text-[var(--varnarc-brand)]" href="/hr/payroll/payslips">
            Open payslips
          </Link>
        </p>
      </HrPanel>
      <div className="mb-8">
        <HrDataTable
          columns={['Employee', 'Basic', 'HRA', 'Special', 'LTA', 'Professional tax', 'PF']}
          empty="No salaries yet."
          rows={(salaries.data ?? []).map((row) => [
            `${row.employee.fullName} (${row.employee.employeeCode})`,
            money(row.basic),
            money(row.hra),
            money(row.specialAllowance),
            money(row.leaveTravelAllowance),
            money(row.professionalTax),
            money(row.providentFund),
          ])}
        />
      </div>
      <HrDataTable
        columns={['Period', 'Status', 'Payslips']}
        empty="No payroll runs yet."
        rows={(runs.data ?? []).map((row) => [row.period, row.status, row._count.payslips])}
      />
    </div>
  );
}
