'use client';

import { useState } from 'react';
import { Button } from '@varnarc/ui';

type CompanyProfile = {
  legalName?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country?: string | null;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  gstin?: string | null;
  pan?: string | null;
  cin?: string | null;
  logoUrl?: string | null;
  payslipGeneratedBy?: string | null;
};

const FIELD_LABELS: Record<keyof CompanyProfile, string> = {
  legalName: 'Legal name',
  address: 'Address',
  city: 'City',
  state: 'State',
  postalCode: 'Postal code',
  country: 'Country',
  email: 'Email',
  phone: 'Phone',
  website: 'Website',
  gstin: 'GSTIN',
  pan: 'Company PAN',
  cin: 'CIN',
  logoUrl: 'Logo URL',
  payslipGeneratedBy: 'Payslip generated by',
};

type ApiIssue = {
  path?: Array<string | number>;
  message?: string;
  unionErrors?: Array<{ issues?: ApiIssue[] }>;
};

function collectIssues(issue: ApiIssue, into: Array<{ field: string; message: string }>) {
  if (issue.unionErrors?.length) {
    for (const entry of issue.unionErrors) {
      for (const nested of entry.issues ?? []) collectIssues(nested, into);
    }
    return;
  }
  if (!issue.message) return;
  into.push({
    field: (issue.path ?? []).map(String).join('.'),
    message: issue.message,
  });
}

function fieldErrorsFromDetails(details: unknown): Record<string, string> {
  if (!Array.isArray(details)) return {};
  const issues: Array<{ field: string; message: string }> = [];
  for (const item of details) {
    if (item && typeof item === 'object') collectIssues(item as ApiIssue, issues);
  }
  const next: Record<string, string> = {};
  for (const issue of issues) {
    const label = FIELD_LABELS[issue.field as keyof CompanyProfile] ?? (issue.field || 'Form');
    const line = `${label}: ${issue.message}`;
    next[issue.field || 'form'] = next[issue.field || 'form']
      ? `${next[issue.field || 'form']} ${issue.message}`
      : line;
  }
  return next;
}

const inputClass = 'mt-1 block h-10 w-full rounded-md border px-3';

export function CompanyProfileForm({ initial }: { initial: CompanyProfile }) {
  const [form, setForm] = useState<CompanyProfile>(initial);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [message, setMessage] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);

  function update<K extends keyof CompanyProfile>(key: K, value: CompanyProfile[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
    setFieldErrors((prev) => {
      if (!prev[key]) return prev;
      const next = { ...prev };
      delete next[key];
      return next;
    });
    setSaved(false);
  }

  async function save() {
    setMessage(null);
    setSaved(false);
    setFieldErrors({});
    const res = await fetch('/api/admin/settings/company', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form),
    });
    const json = (await res.json().catch(() => ({}))) as {
      error?: { message?: string; details?: unknown };
    };
    if (!res.ok) {
      const errors = fieldErrorsFromDetails(json.error?.details);
      if (Object.keys(errors).length > 0) {
        setFieldErrors(errors);
        setMessage('Fix the fields below, then save again.');
        return;
      }
      setMessage(json.error?.message || 'Save failed');
      return;
    }
    setSaved(true);
    setMessage('Saved. Payslips and other company details use this profile.');
  }

  function fieldClass(name: keyof CompanyProfile, multiline = false) {
    const invalid = Boolean(fieldErrors[name]);
    return `${multiline ? 'mt-1 w-full rounded-md border p-3 text-sm' : inputClass} ${
      invalid ? 'border-red-500' : 'border-[var(--varnarc-border)]'
    }`;
  }

  function fieldError(name: keyof CompanyProfile) {
    const text = fieldErrors[name];
    if (!text) return null;
    return (
      <p className="mt-1 text-sm text-red-600" role="alert">
        {text}
      </p>
    );
  }

  const summary = Object.entries(fieldErrors).filter(([key]) => !(key in FIELD_LABELS));

  return (
    <div className="space-y-4 rounded-lg border border-[var(--varnarc-border)] bg-[var(--varnarc-surface)] p-4">
      {message ? (
        <p
          className={`text-sm ${saved ? 'text-[var(--varnarc-subtle)]' : 'text-red-600'}`}
          role="alert"
        >
          {message}
        </p>
      ) : null}
      {Object.keys(fieldErrors).length > 0 ? (
        <ul className="list-disc space-y-1 pl-5 text-sm text-red-600" role="alert">
          {Object.entries(fieldErrors)
            .filter(([key]) => key in FIELD_LABELS)
            .map(([key, text]) => (
              <li key={key}>{text}</li>
            ))}
          {summary.map(([key, text]) => (
            <li key={key}>{text}</li>
          ))}
        </ul>
      ) : null}
      <div className="grid gap-4 md:grid-cols-2">
        <label className="block text-sm md:col-span-2">
          Legal name
          <input
            className={fieldClass('legalName')}
            aria-invalid={Boolean(fieldErrors.legalName)}
            value={form.legalName ?? ''}
            onChange={(event) => update('legalName', event.target.value || null)}
          />
          {fieldError('legalName')}
        </label>
        <label className="block text-sm md:col-span-2">
          Address
          <textarea
            className={fieldClass('address', true)}
            aria-invalid={Boolean(fieldErrors.address)}
            rows={2}
            value={form.address ?? ''}
            onChange={(event) => update('address', event.target.value || null)}
          />
          {fieldError('address')}
        </label>
        <label className="block text-sm">
          City
          <input
            className={fieldClass('city')}
            aria-invalid={Boolean(fieldErrors.city)}
            value={form.city ?? ''}
            onChange={(event) => update('city', event.target.value || null)}
          />
          {fieldError('city')}
        </label>
        <label className="block text-sm">
          State
          <input
            className={fieldClass('state')}
            aria-invalid={Boolean(fieldErrors.state)}
            value={form.state ?? ''}
            onChange={(event) => update('state', event.target.value || null)}
          />
          {fieldError('state')}
        </label>
        <label className="block text-sm">
          Postal code
          <input
            className={fieldClass('postalCode')}
            aria-invalid={Boolean(fieldErrors.postalCode)}
            value={form.postalCode ?? ''}
            onChange={(event) => update('postalCode', event.target.value || null)}
          />
          {fieldError('postalCode')}
        </label>
        <label className="block text-sm">
          Country
          <input
            className={fieldClass('country')}
            aria-invalid={Boolean(fieldErrors.country)}
            value={form.country ?? ''}
            onChange={(event) => update('country', event.target.value || null)}
          />
          {fieldError('country')}
        </label>
        <label className="block text-sm">
          Email
          <input
            type="email"
            className={fieldClass('email')}
            aria-invalid={Boolean(fieldErrors.email)}
            value={form.email ?? ''}
            onChange={(event) => update('email', event.target.value || null)}
          />
          {fieldError('email')}
        </label>
        <label className="block text-sm">
          Phone
          <input
            className={fieldClass('phone')}
            aria-invalid={Boolean(fieldErrors.phone)}
            value={form.phone ?? ''}
            onChange={(event) => update('phone', event.target.value || null)}
          />
          {fieldError('phone')}
        </label>
        <label className="block text-sm">
          Website
          <input
            className={fieldClass('website')}
            aria-invalid={Boolean(fieldErrors.website)}
            value={form.website ?? ''}
            onChange={(event) => update('website', event.target.value || null)}
          />
          {fieldError('website')}
        </label>
        <label className="block text-sm">
          Logo URL
          <input
            className={fieldClass('logoUrl')}
            aria-invalid={Boolean(fieldErrors.logoUrl)}
            value={form.logoUrl ?? ''}
            onChange={(event) => update('logoUrl', event.target.value || null)}
          />
          {fieldError('logoUrl')}
        </label>
        <label className="block text-sm">
          GSTIN
          <input
            className={fieldClass('gstin')}
            aria-invalid={Boolean(fieldErrors.gstin)}
            value={form.gstin ?? ''}
            onChange={(event) => update('gstin', event.target.value || null)}
          />
          {fieldError('gstin')}
        </label>
        <label className="block text-sm">
          Company PAN
          <input
            className={fieldClass('pan')}
            aria-invalid={Boolean(fieldErrors.pan)}
            value={form.pan ?? ''}
            maxLength={10}
            onChange={(event) => update('pan', event.target.value || null)}
          />
          {fieldError('pan')}
        </label>
        <label className="block text-sm">
          CIN
          <input
            className={fieldClass('cin')}
            aria-invalid={Boolean(fieldErrors.cin)}
            value={form.cin ?? ''}
            onChange={(event) => update('cin', event.target.value || null)}
          />
          {fieldError('cin')}
        </label>
        <label className="block text-sm">
          Payslip generated by
          <input
            className={fieldClass('payslipGeneratedBy')}
            aria-invalid={Boolean(fieldErrors.payslipGeneratedBy)}
            value={form.payslipGeneratedBy ?? ''}
            onChange={(event) => update('payslipGeneratedBy', event.target.value || null)}
          />
          {fieldError('payslipGeneratedBy')}
        </label>
      </div>
      <Button
        type="button"
        onClick={() =>
          void save().catch((error) => {
            setSaved(false);
            setMessage(error instanceof Error ? error.message : 'Save failed');
          })
        }
      >
        Save company profile
      </Button>
    </div>
  );
}
