CREATE TYPE "CrmLaptopCategory" AS ENUM ('WINDOWS_LAPTOP', 'APPLE_LAPTOP');
CREATE TYPE "CrmLaptopAvailability" AS ENUM ('IN_STOCK', 'OUT_OF_STOCK', 'VARIES');

ALTER TABLE "crm_laptops"
  ADD COLUMN "monthly_rate" DECIMAL(12,2),
  ADD COLUMN "commitment_months" INTEGER NOT NULL DEFAULT 12,
  ADD COLUMN "commitment_rate" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "gst_percent" DECIMAL(5,2) NOT NULL DEFAULT 18,
  ADD COLUMN "deposit_per_laptop" DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN "name" TEXT,
  ADD COLUMN "slug" TEXT,
  ADD COLUMN "category" "CrmLaptopCategory" NOT NULL DEFAULT 'WINDOWS_LAPTOP',
  ADD COLUMN "listed_year" INTEGER,
  ADD COLUMN "generation" TEXT,
  ADD COLUMN "processor_full" TEXT,
  ADD COLUMN "graphics" TEXT,
  ADD COLUMN "camera" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "model_number" TEXT,
  ADD COLUMN "ports" TEXT,
  ADD COLUMN "adapter" TEXT,
  ADD COLUMN "use_case" TEXT,
  ADD COLUMN "taxes_note" TEXT,
  ADD COLUMN "availability" "CrmLaptopAvailability" NOT NULL DEFAULT 'IN_STOCK';

UPDATE "crm_laptops"
SET
  "name" = COALESCE(NULLIF(BTRIM(CONCAT("brand", ' ', COALESCE("model", ''))), ''), "asset_tag", 'Laptop'),
  "slug" = LOWER(REGEXP_REPLACE(COALESCE("asset_tag", "id"::text), '[^a-zA-Z0-9]+', '-', 'g'))
WHERE "name" IS NULL;

ALTER TABLE "crm_laptops" ALTER COLUMN "name" SET NOT NULL;
ALTER TABLE "crm_laptops" ALTER COLUMN "asset_tag" DROP NOT NULL;
ALTER TABLE "crm_laptops" ALTER COLUMN "serial_number" DROP NOT NULL;
ALTER TABLE "crm_laptops" ALTER COLUMN "ram" DROP NOT NULL;
ALTER TABLE "crm_laptops" ALTER COLUMN "storage" DROP NOT NULL;
ALTER TABLE "crm_laptops" ALTER COLUMN "display" DROP NOT NULL;

CREATE UNIQUE INDEX "crm_laptops_slug_key" ON "crm_laptops"("slug");
CREATE INDEX "crm_laptops_category_idx" ON "crm_laptops"("category");

INSERT INTO "crm_laptops" (
  "id", "name", "slug", "category", "brand", "model", "listed_year", "generation", "processor", "processor_full",
  "ram", "storage", "display", "graphics", "camera", "operating_system", "model_number", "ports", "adapter", "use_case",
  "monthly_rate", "commitment_months", "commitment_rate", "gst_percent", "deposit_per_laptop", "taxes_note", "availability", "status",
  "created_at", "updated_at"
) VALUES
  (gen_random_uuid(), 'Dell Latitude (2015) - i5', 'dell-latitude-2015-i5', 'WINDOWS_LAPTOP', 'Dell', 'Latitude', 2015, '5th/6th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 10 Pro', NULL, NULL, NULL, NULL, 1900, 12, 1352, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Elitebook (2016) - i5', 'hp-elitebook-2016-i5', 'WINDOWS_LAPTOP', 'HP', 'Elitebook', 2016, '6th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 10 Pro', NULL, NULL, NULL, NULL, 1900, 12, 1352, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Elitebook Touch (2016) - i7', 'hp-elitebook-touch-2016-i7', 'WINDOWS_LAPTOP', 'HP', 'Elitebook Touch', 2016, '6th', 'Intel Core i7', 'Intel Core i7-6600U @ 2.60GHz', '8GB / 16GB', '256GB SSD / 512GB SSD', '14"', 'Intel HD Graphics 520', true, 'Windows 10 Pro', 'HP EliteBook 840 G3', NULL, NULL, 'Light browsing; heavier Office files benefit from 16GB RAM', 2300, 12, 1636, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Latitude Touch (2016) - i7', 'dell-latitude-touch-2016-i7', 'WINDOWS_LAPTOP', 'Dell', 'Latitude Touch', 2016, '6th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 10 Pro', NULL, NULL, NULL, NULL, 2300, 12, 1636, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Precision (2016) - i7', 'dell-precision-2016-i7', 'WINDOWS_LAPTOP', 'Dell', 'Precision', 2016, '6th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 10 Pro', NULL, NULL, NULL, NULL, 2900, 12, 2063, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Latitude (2018) - i5', 'dell-latitude-2018-i5', 'WINDOWS_LAPTOP', 'Dell', 'Latitude', 2018, '8th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 3500, 12, 2489, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Latitude (2018) - i7', 'dell-latitude-2018-i7', 'WINDOWS_LAPTOP', 'Dell', 'Latitude', 2018, '8th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 4000, 12, 2845, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Latitude (2020) - i3', 'dell-latitude-2020-i3', 'WINDOWS_LAPTOP', 'Dell', 'Latitude', 2020, '10th', 'Intel Core i3', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 4000, 12, 2845, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell/ Lenovo (2020) - i5', 'dell-lenovo-2020-i5', 'WINDOWS_LAPTOP', 'Dell/Lenovo', 'Business Laptop', 2020, '10th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 4500, 12, 3200, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell/ Lenovo (2021) - i5', 'dell-lenovo-2021-i5', 'WINDOWS_LAPTOP', 'Dell/Lenovo', 'Business Laptop', 2021, '11th', 'Intel Core i5', 'Intel Core i5-1145G7 @ 2.60GHz', '16GB / 32GB', '512GB SSD / 1TB SSD', '14"', 'Intel Iris Xe Graphics', true, 'Windows 11 Pro', 'Dell Latitude 3420/5420/5510 i5', NULL, NULL, 'Basic to moderate design/coding work', 4800, 12, 3414, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Lenovo Thinkpad (2020) - i7', 'lenovo-thinkpad-2020-i7', 'WINDOWS_LAPTOP', 'Lenovo', 'ThinkPad', 2020, '10th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 4800, 12, 3414, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Latitude (2021) - i7', 'dell-latitude-2021-i7', 'WINDOWS_LAPTOP', 'Dell', 'Latitude', 2021, '11th', 'Intel Core i7', 'Intel Core i7-1185G7 @ 3.00GHz', '16GB / 32GB', '512GB SSD / 1TB SSD', '14"', 'Intel Iris Xe Graphics', true, 'Windows 11 Pro', 'Dell Latitude 3420/5420 i7', NULL, NULL, 'Useful for heavy workload', 4900, 12, 3485, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Lenovo V15 (2023) - i3', 'lenovo-v15-2023-i3', 'WINDOWS_LAPTOP', 'Lenovo', 'V15', 2023, '13th', 'Intel Core i3', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 4900, 12, 3485, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Elitebook G9 (2022) - i5', 'hp-elitebook-g9-2022-i5', 'WINDOWS_LAPTOP', 'HP', 'Elitebook G9', 2022, '12th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 5300, 12, 3769, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Lenovo V14 (2023) - i5', 'lenovo-v14-2023-i5', 'WINDOWS_LAPTOP', 'Lenovo', 'V14', 2023, '13th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 5500, 12, 3912, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP ProBook 450 G8 (2021) - i5', 'hp-probook-450-g8-2021-i5', 'WINDOWS_LAPTOP', 'HP', 'ProBook 450 G8', 2021, '11th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11', NULL, NULL, NULL, NULL, 5500, 12, 3912, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Latitude 5440 (2023) - i5', 'dell-latitude-5440-2023-i5', 'WINDOWS_LAPTOP', 'Dell', 'Latitude 5440', 2023, '13th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 5500, 12, 3912, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Elitebook G9 (2022) - i7', 'hp-elitebook-g9-2022-i7', 'WINDOWS_LAPTOP', 'HP', 'Elitebook G9', 2022, '12th', 'Intel Core i7', 'Intel Core i7-1255U @ 1.70GHz', '16GB DDR4', '512GB SSD', '14" FHD', 'Intel Iris Xe Graphics', true, 'Windows 11 Pro', 'HP Elitebook 640 G9 Notebook PC', NULL, NULL, NULL, 5800, 12, 4125, 18, 5000, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Inspiron (2023) - i7', 'dell-inspiron-2023-i7', 'WINDOWS_LAPTOP', 'Dell', 'Inspiron', 2023, '13th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 6000, 12, 4267, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'IdeaPad Slim 3 (2023) - i7', 'ideapad-slim-3-2023-i7', 'WINDOWS_LAPTOP', 'Lenovo', 'IdeaPad Slim 3', 2023, '13th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 6000, 12, 4267, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Latitude 5450 (2023) - Ultra i7', 'dell-latitude-5450-2023-ultra-i7', 'WINDOWS_LAPTOP', 'Dell', 'Latitude 5450', 2023, '13th', 'Intel Core Ultra 7', 'Intel Core Ultra 7 135U (12-core)', '16GB DDR5', '512GB NVMe SSD', '14" FHD 1920x1080 touchscreen', 'Intel Graphics with Intel AI Boost', true, 'Windows 11 Pro', 'Dell Latitude 5450 AI Powered Laptop', 'Thunderbolt 4', '65W USB-C', NULL, 7100, 12, 5049, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Lenovo LOQ - RTX 2050', 'lenovo-loq-rtx-2050', 'WINDOWS_LAPTOP', 'Lenovo', 'LOQ', NULL, '12th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 7200, 12, 5120, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Victus - RTX 2050', 'hp-victus-rtx-2050', 'WINDOWS_LAPTOP', 'HP', 'Victus', NULL, '12th/13th', 'AMD Ryzen 7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11', NULL, NULL, NULL, NULL, 7600, 12, 5405, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Lenovo LOQ - RTX 3050', 'lenovo-loq-rtx-3050', 'WINDOWS_LAPTOP', 'Lenovo', 'LOQ', NULL, '13th', 'AMD Ryzen 5', 'AMD Ryzen 5 7235HS, 3.2–4.2GHz, 4 cores/8 threads', '12GB / 16GB / 32GB', '512GB / 1TB', '15.6"', 'NVIDIA GeForce RTX 3050 4GB GDDR6', true, 'Windows 11 Pro', 'Lenovo LOQ 83JC00HNIN', NULL, NULL, NULL, 7900, 12, 5618, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Victus - RTX 3050', 'hp-victus-rtx-3050', 'WINDOWS_LAPTOP', 'HP', 'Victus', NULL, '12th/13th', 'AMD Ryzen 7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11', NULL, NULL, NULL, NULL, 8100, 12, 5760, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Victus - RTX 4050', 'hp-victus-rtx-4050', 'WINDOWS_LAPTOP', 'HP', 'Victus', NULL, '12th/13th', 'AMD Ryzen 7', 'AMD Ryzen 7', '16GB / 32GB', '512GB / 1TB', '15.6"', 'NVIDIA GeForce RTX 4050 6GB GDDR6', true, 'Windows 11', 'HP Victus', NULL, NULL, NULL, 8500, 12, 6045, 18, 5000, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'HP Victus - i7 - RTX 4050', 'hp-victus-i7-rtx-4050', 'WINDOWS_LAPTOP', 'HP', 'Victus', NULL, '12th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 8500, 12, 6045, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Dell Precision - i7 - RTX 3000', 'dell-precision-i7-rtx-3000', 'WINDOWS_LAPTOP', 'Dell', 'Precision', NULL, '10th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'Windows 11 Pro', NULL, NULL, NULL, NULL, 9100, 12, 6472, 18, 0, 'Additional charges may apply at checkout', 'VARIES', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Air (2017) - i5', 'mac-air-2017-i5', 'APPLE_LAPTOP', 'Apple', 'MacBook Air', 2017, '5th', 'Intel Core i5', NULL, NULL, NULL, NULL, NULL, false, 'macOS Monterey', NULL, NULL, NULL, NULL, 3700, 12, 2632, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro (2015) - i7', 'mac-pro-2015-i7', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', 2015, '4th', 'Intel Core i7', 'Quad-core Intel Core i7 (2.2–2.8 GHz, 4 cores, 8 threads)', '16GB', '256GB SSD', '15.4"', 'Intel Iris Pro 5200 + AMD Radeon R9 M370X 2GB', true, 'macOS Monterey', 'MJLQ2HN/A', NULL, NULL, 'Best for basic design work', 3900, 12, 2774, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - i7 (7th gen)', 'mac-pro-i7-7th-gen', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '7th', 'Intel Core i7', NULL, NULL, NULL, NULL, NULL, false, 'macOS Ventura', NULL, NULL, NULL, NULL, 5200, 12, 3698, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - i7 (8th gen)', 'mac-pro-i7-8th-gen', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', 2018, '8th/9th', 'Intel Core i7', '2.6 GHz 6-Core Intel Core i7', '16GB', '256GB SSD / 512GB SSD', '15.4"', 'Intel UHD Graphics 630 + AMD Radeon Pro 560X 4GB', true, 'macOS Sequoia', 'MR972HN/A or MR942N/A or MVJJ2HN/A or MV902HN/A', NULL, NULL, 'Best for coders and designers on budget', 5400, 12, 3840, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - i9', 'mac-pro-i9', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', 2019, '9th', 'Intel Core i9', '8-Core Intel Core i9-9800H', '16GB / 64GB', '512GB SSD', '15.4"', 'Intel UHD Graphics 630 + AMD Radeon Pro 560X 4GB', true, 'macOS Sequoia', 'MV912HN/A or MVVK2HN/A', NULL, NULL, 'Best for coders and designers who need a 15.4" screen', 5900, 12, 4196, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Air - M1 Chip', 'mac-air-m1-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Air', 2020, '1st', 'Apple M1', 'Apple M1 8-core (4 performance + 4 efficiency)', '8GB / 16GB', '256GB SSD', '13.3"', 'Integrated 7-core GPU', true, 'macOS Tahoe', 'MGN63HN/A or MGN73HN/A', NULL, NULL, 'Best for designers on budget for M-chip', 6000, 12, 4267, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Air - M2 Chip', 'mac-air-m2-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Air', 2022, '2nd', 'Apple M2', 'Apple M2 8-core (4 performance + 4 efficiency)', '16GB', '256GB SSD', '13.6"', 'Integrated 8-core GPU', true, 'macOS Tahoe', 'MC7X4HN/A', NULL, NULL, 'Best for moderate to high design work', 6700, 12, 4765, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M1 chip', 'mac-pro-m1-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '1st', 'Apple M1', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 6700, 12, 4765, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M2 Chip', 'mac-pro-m2-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '2nd', 'Apple M2', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 8200, 12, 5832, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M1 Chip - 16gb', 'mac-pro-m1-chip-16gb', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '1st', 'Apple M1', NULL, NULL, NULL, NULL, NULL, false, 'macOS 15/Tahoe', NULL, NULL, NULL, NULL, 8800, 12, 6258, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Air - M3 Chip', 'mac-air-m3-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Air', NULL, '3rd', 'Apple M3', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 9000, 12, 6400, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Air - M4 Chip', 'mac-air-m4-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Air', NULL, '4th', 'Apple M4', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 9200, 12, 6543, 18, 0, 'Additional charges may apply at checkout', 'VARIES', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M1 Pro Chip', 'mac-pro-m1-pro-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', 2021, '1st', 'Apple M1 Pro', 'Apple M1 Pro 10-core (8 performance + 2 efficiency)', '16GB / 32GB', '512GB SSD', '14" / 16"', 'Integrated 14-core GPU', true, 'macOS Tahoe', 'MKGP3HN/A', NULL, NULL, 'Best for heavy coding/designing work', 10000, 12, 7111, 18, 5000, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M1 Max', 'mac-pro-m1-max', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '1st', 'Apple M1 Max', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 12000, 12, 8534, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M4 Chip', 'mac-pro-m4-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', 2024, '4th', 'Apple M4', 'Apple M4 10-core (4 performance + 6 efficiency)', '16GB', '512GB SSD', '14"', 'Integrated 10-core GPU', true, 'macOS Tahoe', 'MW2W3HN/A', NULL, NULL, 'Best for heavy coding/designing work', 12500, 12, 8889, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M5 Chip', 'mac-pro-m5-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '5th', 'Apple M5', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 14500, 12, 10311, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M3 Pro Chip', 'mac-pro-m3-pro-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '3rd', 'Apple M3 Pro', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 14500, 12, 10311, 18, 0, 'Additional charges may apply at checkout', 'IN_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M4 Pro Chip', 'mac-pro-m4-pro-chip', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '4th', 'Apple M4 Pro', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, 16000, 12, 11378, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW()),
  (gen_random_uuid(), 'Mac Pro - M4 Max', 'mac-pro-m4-max', 'APPLE_LAPTOP', 'Apple', 'MacBook Pro', NULL, '4th', 'Apple M4 Max', NULL, NULL, NULL, NULL, NULL, false, 'macOS Tahoe', NULL, NULL, NULL, NULL, NULL, 12, 18489, 18, 0, 'Additional charges may apply at checkout', 'OUT_OF_STOCK', 'AVAILABLE', NOW(), NOW())
ON CONFLICT ("slug") DO NOTHING;
